# Generated by Django 2.2.3 on 2019-08-09 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.IntegerField(default=0)),
                ('day', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('calories', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('age', models.DateField()),
                ('sex', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MealProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pal_app.Meal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pal_app.Product')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='products',
            field=models.ManyToManyField(through='pal_app.MealProducts', to='pal_app.Product'),
        ),
    ]
