# Generated by Django 2.2.3 on 2019-07-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pal_app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='pal_app.Product')),
            ],
        ),
    ]
