# Generated by Django 2.2.3 on 2019-07-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pal_app', '0004_meal_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.IntegerField(default=0),
        ),
    ]
