# Generated by Django 2.2.3 on 2019-08-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pal_app', '0005_meal_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DateField(),
        ),
    ]
